<table width="80%" border="1" cellspacing="0" class="redTable">
  <tr>
    <th colspan="3">Nesting Level 2 - This table is part of the nested include file nested.inc.<br>header.inc includes nested.inc.</th>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td><img src="../images/dw_cs3_logo.jpg"></td>
    <td>&nbsp;</td>
  </tr>
</table>