<p>This is from pager.inc</p>
<p>Test links for Live View Nav integration:</p>
<p><a href="../css/html/A_file_w_css.htm">Link to A_file_w_css.htm</a> - TC1; a simple HTML file w/ an external CSS file; no DRF; in the same site as this file</p>
<p><a href="../wordpress_model/index.php">Link to wordpress_model</a> - TC3; site defined for this; in the same site as this file; has its own different DRF</p>
<p><a href="../php/main3.php">Link to main3.php</a> - a PHP file that has static path PHP includes; in the same site as this file</p>
<p><a href="../coldfusion/main.cfm">Link to main.cfm</a> - a ColdFusion file that has static path CF includes; in the same site as this file</p>
<p><a href="http://drupal.org">Link to drupal.org</a> - no site defined for this</p>
<p><a href="http://wordpress.org">Link to wordpress.org</a> - no site defined for this</p>
<p><a href="http://dreamqe01.corp.adobe.com/wordpress">Link to dreamqe01/wordpress</a> - TC4; site defined for this</p>
<p><a href="http://www.microsoft.com">Link to microsoft.com</a> - no site defined for this</p>
<p><a href="http://www.yahoo.com">Link to yahoo.com</a> - no site defined for this</p>
</body>
</html>