<html>
<head>
<title>Drupal simple model</title>
<link href="/DRF/drupal_model/themes/garland/style1_öäüßZ.css?6" rel="stylesheet" type="text/css" />
<style type="text/css">
<!--
@import url("/DRF/drupal_model/themes/garland/style2_カスタムカラ.css?6");
-->
</style>
<link href="/DRF/drupal_model/themes/garland/style3.css?6" rel="stylesheet" type="text/css" />
<script type="text/javascript" src="/DRF/drupal_model/misc/jquery.js?6"></script>
<script type="text/javascript">
<!--
var ds1 = new Spry.Data.XMLDataSet("/DRF/drupal_model/themes/garland/specials.xml", "specials/menu_item");
//-->
</script>
</head>
<body>
<p>This is from theme.inc. theme.inc references the following files:
<ul>
<li>style.css using a link tag</li>
<li>style2.css using @import</li>
<li>jquery.js using a script tag</li>
<li>specials.xml using a script tag with Spry.Data.XMLDataSet</li>
</ul>
</p>